PATH_STOCKS = '../data/stock/stocks.csv'
FORMAT_SELECTED = '../data/stock/selected_{}.csv'
FORMAT_HISTORY = '../data/history/daily_{}.csv'
FORMAT_STUDY = '../data/study/study_{}.csv'
PATH_FINANCIALS = '../data/fundamentals/financials.json'
PATH_PEERS = '../data/fundamentals/peers.json'
PATH_STATS = '../data/fundamentals/stats.json'
STOCK_A = 'AAPL'
